backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
  - name: "teams"
    label: "Teams"
    files:
      - file: "site/content/teams/_index.md"
        label: "Team Infos"
        name: "team_infos"
        delete: false # Prevent users from deleting documents in this collection
        editor:
          preview: false
        fields:
          - {label: Teams, name: teams, widget: list, fields: [
              {label: Team city, name: team_city, widget: string},
              {label: Team name, name: team_name, widget: string},
              {label: Team ID, name: team_id, widget: string, hint: "Los Angeles Rebels should be something like 'lar'."},
              {label: Image, name: image, widget: image, required: false},
              {label: "Conference/Division", name: "division", widget: "select", options: [{ label: { label: "North East", value: "northeast" }, "North West", value: "northwest" }, { label: "South East", value: "southeast" }, { label: "South West", value: "southwest" }], required: false},
              {label: Text, name: text, widget: text, required: false}]}
  - name: "trades" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Trades" # Used in the UI, ie.: "New Post"
    folder: "site/content/trade" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "ID", name: "id", widget: "string", hint: "Should be unique, use season_day_team1_team2_no format, e.g.: '2001_03_vegas_edmonton_1'."}
      - label: "Day"
        name: "day"
        widget: "number"
        value_type: "int"
        min: 0
        max: 45
        step: 1
        hint: "A Number from 0 to 45"
      - label: "Season"
        name: "season"
        widget: "number"
        value_type: "int"
        min: 2000
        max: 3000
        step: 10
        hint: "E.g. '2008'"
      - label: "Team A"
        name: team_a
        widget: object
        fields:
          - label: "Team A"
            name: "team"
            widget: "relation"
            collection: "teams"
            file: "team_infos"
            search_fields: ["teams.*.team_city", "teams.*.team_name"]
            value_field: "teams.*.team_name"
            display_fields: ["teams.*.team_city", "teams.*.team_name"]
          - label: "Sending Players"
            name: "players"
            widget: "string"
            hint: "Separate by comma, e.g. 'John Doe, Jim Smith'"
          - label: "Sending Cash"
            name: "cash"
            widget: "number"
            default: 2
            value_type: "int"
            min: 1
            hint: "E.g. '1000000'"
      - label: "Team B"
        name: team_b
        widget: object
        fields:
        - label: "Team B"
          name: "team"
          widget: "relation"
          collection: "teams"
          file: "team_infos"
          search_fields: ["teams.*.team_city", "teams.*.team_name"]
          value_field: "teams.*.team_name"
          display_fields: ["teams.*.team_city", "teams.*.team_name"]
        - label: "Sending Players"
          name: "players"
          widget: "string"
          default: "Don Mason"
        - label: "Sending Cash"
          name: "cash"
          widget: "number"
          value_type: "int"
          min: 1
      - {label: "Additional Info", name: "info", widget: "text"}